version: '3.8'
services:
  catalogue:
    build:
      context: ./catalogue
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./catalogue:/app
    networks:
      - devflix-network

networks:
  devflix-network:
    driver: bridge