# services:
#   catalogue:
#     build:
#       context: ./catalogue
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./catalogue:/app
#     networks:
#       - devflix-network

# networks:
#   devflix-network:
#     driver: bridge


version: '3.8'

services:
  catalogue:
    build: ./catalogue
    ports:
      - "5000:5000"
    volumes:
      - ./catalogue:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app/src
    command: ["node", "app.js"]

  recommendation:
    build: ./recommendation
    ports:
      - "8082:8082"
