# Stage 1: Build
FROM golang:1.21 as builder

WORKDIR /app
COPY . .
RUN go mod init devflix/recommendation && go build -o main

# Stage 2: Run
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .

EXPOSE 8082
CMD ["./main"]
